---
servers:
- url: ''
openapi: 3.0.3
info:
  description: API Description
  title: Voting Guide API
  version: 1.0.0
paths:
  "/suggest":
    get:
      description: ''
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
        default:
          description: Default response.
      parameters:
      - name: q
        description: The query string for address suggestions
        in: query
        required: false
        schema:
          type: string
          default: ''
  "/details":
    get:
      description: ''
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
        default:
          description: Default response.
      parameters:
      - name: address
        description: The full address to get details for
        in: query
        required: false
        schema:
          type: string
          default: ''

